cp /usr/portage/net-nds/openldap/files/openldap-2.4.17-gcc44.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.2.14-perlthreadsfix.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.15-ppolicy.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.35-contrib-smbk5pwd.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.35-contrib-samba4.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.11-libldap_r.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.17-fix-lmpasswd-gnutls-symbols.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.28-gnutls-gcrypt.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.6-evolution-ntlm.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.28-fix-dash.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.31-gcc47.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.42-mdb-unbundle.patch .
cp /usr/portage/net-nds/openldap/files/openldap-2.4.40-slapd-conf .
cp /usr/portage/net-nds/openldap/files/slapd-initd-2.4.40-r2 .
cp /usr/portage/net-nds/openldap/files/slapd-confd-2.4.28-r1 .
cp /usr/portage/net-nds/openldap/files/slapd.service .
cp /usr/portage/net-nds/openldap/files/slapd.service.conf .
cp /usr/portage/net-nds/openldap/files/slapd.tmpfilesd .
cp /usr/portage/net-nds/openldap/files/DB_CONFIG.fast.example .
